"""Bilingual Salon Codex localization helpers."""

from __future__ import annotations

from typing import Any

from aulos_skills.salon_codex import SALON_DICT_KEYS, SALON_LIST_KEYS, SALON_SCALAR_KEYS, empty_dossier, merge_dossiers


UI_COPY = {
    "en": {
        "eyebrow": "Aulos · Salon Codex listening guide",
        "lang_en": "English",
        "lang_zh": "中文",
        "composer": "Composer",
        "life": "Life",
        "temperament": "Temperament",
        "oeuvre": "In the oeuvre",
        "history": "In music history",
        "introduction": "The work",
        "genesis": "Genesis & world",
        "stature": "Why it endures",
        "wide": "Wide research",
        "anatomy": "Anatomy of the work",
        "deep": "Deep research",
        "deepdives": "Selected deep dives",
        "map": "Listening map",
        "sound": "Sound world",
        "original_instrument": "Original instrument",
        "ensemble": "Ensemble / scoring",
        "modes": "Modern listening modes",
        "kindred": "Kindred works",
        "interpretations": "Famous interpretations",
        "media": "Listening room media",
        "videos": "YouTube & appreciation",
        "vinyl": "Discogs & vinyl shelf",
        "practice": "How to practice listening",
        "caveats": "Myths & caveats",
        "footer": "Generated by Aulos SkillRuntime — Salon Codex atelier for deep listening.",
        "year": "Year",
        "place": "Place",
        "publication": "Publication",
        "patronage": "Patronage",
        "background": "Background",
        "instrument_culture": "Instrument culture",
        "youtube": "YouTube",
        "discogs": "Discogs",
        "ambient_label": "Theme",
        "ambient_play": "Play",
        "ambient_pause": "Pause",
        "ambient_hint": "Soft background from a related recording — tap play if autoplay is blocked.",
        "ambient_expand": "Info",
        "ambient_collapse": "Hide",
        "ambient_playlist": "Playlist",
        "ambient_playlist_hint": "Full licensed recording — list loops; tap a track to play.",
        "ambient_now": "Now playing",
        "ambient_why": "Why this music",
    },
    "zh": {
        "eyebrow": "Aulos · 沙龙典藏导赏",
        "lang_en": "English",
        "lang_zh": "中文",
        "composer": "作曲家",
        "life": "生平概要",
        "temperament": "气质与写作性格",
        "oeuvre": "在其创作中的位置",
        "history": "在音乐史上的位置",
        "introduction": "作品导读",
        "genesis": "创作背景与时代",
        "stature": "何以传世",
        "wide": "广域研究",
        "anatomy": "作品解剖",
        "deep": "深度听法",
        "deepdives": "重点细读",
        "map": "聆听地图",
        "sound": "声响世界",
        "original_instrument": "原作声响与乐器",
        "ensemble": "编制与演奏形态",
        "modes": "今日可取的聆听方式",
        "kindred": "关联作品",
        "interpretations": "名家演绎",
        "media": "聆听室 · 影音与唱片",
        "videos": "影像与导赏路径",
        "vinyl": "唱片目录与黑胶线索",
        "practice": "如何练习聆听",
        "caveats": "传说与存疑",
        "footer": "由 Aulos 技能运行时生成 — 沙龙典藏导赏工坊。",
        "year": "年代",
        "place": "地点",
        "publication": "出版",
        "patronage": "赞助与题献",
        "background": "创作语境",
        "instrument_culture": "乐器与演奏文化",
        "youtube": "YouTube 欣赏",
        "discogs": "Discogs 唱片",
        "ambient_label": "主题",
        "ambient_play": "播放",
        "ambient_pause": "暂停",
        "ambient_hint": "相关录音作轻声背景；若浏览器拦截自动播放，请轻点播放。",
        "ambient_expand": "说明",
        "ambient_collapse": "收起",
        "ambient_playlist": "曲目",
        "ambient_playlist_hint": "完整授权录音 · 列表循环；点选曲目即可切换。",
        "ambient_now": "正在播放",
        "ambient_why": "为何选这首",
    },
}


def extract_zh_layer(dossier: dict[str, Any] | None) -> dict[str, Any]:
    d = dict(dossier or {})
    zh = d.get("zh")
    return dict(zh) if isinstance(zh, dict) else {}


def localize_view(dossier: dict[str, Any] | None, lang: str) -> dict[str, Any]:
    """Build a single-language view. English = top-level; Chinese = merge(en, zh)."""
    base = dict(dossier or {})
    zh = extract_zh_layer(base)
    base.pop("zh", None)
    if lang == "zh":
        if not zh:
            # No Chinese pack — return empty markers so UI can show professional fallback
            return empty_dossier()
        # Start from empty then EN structure for media URLs, overlay ZH prose
        scaffold = empty_dossier()
        # Keep shared non-prose: portrait image urls, media links, ambient from EN
        for key in (
            "composer_portrait",
            "interpretations",
            "appreciation_videos",
            "vinyl_and_discography",
            "ambient_audio",
        ):
            if base.get(key):
                scaffold[key] = base[key]
        for key in ("catalog", "composer", "work_title", "era", "form"):
            if base.get(key):
                scaffold[key] = base[key]
        return merge_dossiers(scaffold, zh)
    return base


def dossier_has_zh(dossier: dict[str, Any] | None) -> bool:
    zh = extract_zh_layer(dossier)
    if not zh:
        return False
    # Require real prose, not an empty shell
    if zh.get("listening_thesis") or zh.get("work_introduction"):
        return True
    if zh.get("width_points") or zh.get("depth_points"):
        return True
    if zh.get("composer_profile"):
        return True
    return False


def merge_zh_into(target: dict[str, Any], zh_layer: dict[str, Any] | None) -> dict[str, Any]:
    out = dict(target or {})
    if not zh_layer:
        return out
    existing = extract_zh_layer(out)
    out["zh"] = merge_dossiers(existing, zh_layer)
    return out


def strip_tech_leaks_zh(text: str) -> str:
    """Light hygiene: avoid leaking raw English skill/ops jargon into Chinese copy."""
    banned = (
        "SkillRuntime",
        "corpus_hit",
        "llm_dossier",
        "width_points",
        "TODO",
        "FIXME",
        "null",
        "undefined",
    )
    out = text or ""
    for b in banned:
        out = out.replace(b, "")
    return out.strip()
