"""Salon Codex localization — English + Simplified Chinese + Traditional Chinese."""

from __future__ import annotations

import re
from typing import Any

from aulos_skills.salon_codex import empty_dossier, merge_dossiers

# Public language ids (ISO 15924 script tags — Hans / Hant)
LANG_EN = "en"
LANG_ZH_HANS = "zh-Hans"  # 简体
LANG_ZH_HANT = "zh-Hant"  # 繁体
CHINESE_LANGS = (LANG_ZH_HANS, LANG_ZH_HANT)
CONTENT_LANGS = (LANG_EN, LANG_ZH_HANS, LANG_ZH_HANT)

# Dossier nested keys
_HANS_KEYS = ("zh_hans", "zh-Hans", "zh")
_HANT_KEYS = ("zh_hant", "zh-Hant")


def is_chinese_lang(lang: str) -> bool:
    return (lang or "") in CHINESE_LANGS or (lang or "").startswith("zh")


def normalize_lang(lang: str | None) -> str:
    raw = (lang or "").strip()
    if raw in {"zh", "zh-Hans", "zh_hans", "zh-hans", "hans"}:
        return LANG_ZH_HANS
    if raw in {"zh-Hant", "zh_hant", "zh-hant", "hant"}:
        return LANG_ZH_HANT
    if raw in {LANG_ZH_HANS, LANG_ZH_HANT, LANG_EN}:
        return raw
    return LANG_EN


_UI_EN = {
    "eyebrow": "Aulos · Salon Codex listening guide",
    "lang_en": "English",
    "lang_zh": "中文",
    "lang_zh_hans": "简体",
    "lang_zh_hant": "繁体",
    "composer": "Composer",
    "life": "Life",
    "temperament": "Temperament",
    "oeuvre": "In the oeuvre",
    "history": "In music history",
    "introduction": "The work",
    "genesis": "Genesis & world",
    "stature": "Why it endures",
    "wide": "Wide research",
    "anatomy": "Anatomy of the work",
    "deep": "Deep research",
    "deepdives": "Selected deep dives",
    "map": "Listening map",
    "sound": "Sound world",
    "original_instrument": "Original instrument",
    "ensemble": "Ensemble / scoring",
    "modes": "Modern listening modes",
    "kindred": "Kindred works",
    "interpretations": "Famous interpretations",
    "media": "Listening room media",
    "videos": "YouTube & appreciation",
    "vinyl": "Discogs & vinyl shelf",
    "practice": "How to practice listening",
    "caveats": "Myths & caveats",
    "footer": "Generated by Aulos SkillRuntime — Salon Codex atelier for deep listening.",
    "year": "Year",
    "place": "Place",
    "publication": "Publication",
    "patronage": "Patronage",
    "background": "Background",
    "instrument_culture": "Instrument culture",
    "youtube": "YouTube",
    "discogs": "Discogs",
    "ambient_label": "Theme",
    "ambient_play": "Play",
    "ambient_pause": "Pause",
    "ambient_hint": "Soft background from a related recording — tap play if autoplay is blocked.",
    "ambient_expand": "Info",
    "ambient_collapse": "Hide",
    "ambient_playlist": "Playlist",
    "ambient_playlist_hint": "Full licensed recording — list loops; tap a track to play.",
    "ambient_now": "Now playing",
    "ambient_why": "Why this music",
}

_UI_ZH_HANS = {
    "eyebrow": "Aulos · 沙龙典藏导赏",
    "lang_en": "English",
    "lang_zh": "简体",
    "lang_zh_hans": "简体",
    "lang_zh_hant": "繁体",
    "composer": "作曲家",
    "life": "生平概要",
    "temperament": "气质与写作性格",
    "oeuvre": "在其创作中的位置",
    "history": "在音乐史上的位置",
    "introduction": "作品导读",
    "genesis": "创作背景与时代",
    "stature": "何以传世",
    "wide": "广域研究",
    "anatomy": "作品解剖",
    "deep": "深度听法",
    "deepdives": "重点细读",
    "map": "聆听地图",
    "sound": "声响世界",
    "original_instrument": "原作声响与乐器",
    "ensemble": "编制与演奏形态",
    "modes": "今日可取的聆听方式",
    "kindred": "关联作品",
    "interpretations": "名家演绎",
    "media": "聆听室 · 影音与唱片",
    "videos": "影像与导赏路径",
    "vinyl": "唱片目录与黑胶线索",
    "practice": "如何练习聆听",
    "caveats": "传说与存疑",
    "footer": "由 Aulos 技能运行时生成 — 沙龙典藏导赏工坊。",
    "year": "年代",
    "place": "地点",
    "publication": "出版",
    "patronage": "赞助与题献",
    "background": "创作语境",
    "instrument_culture": "乐器与演奏文化",
    "youtube": "YouTube 欣赏",
    "discogs": "Discogs 唱片",
    "ambient_label": "主题",
    "ambient_play": "播放",
    "ambient_pause": "暂停",
    "ambient_hint": "相关录音作轻声背景；若浏览器拦截自动播放，请轻点播放。",
    "ambient_expand": "说明",
    "ambient_collapse": "收起",
    "ambient_playlist": "曲目",
    "ambient_playlist_hint": "完整授权录音 · 列表循环；点选曲目即可切换。",
    "ambient_now": "正在播放",
    "ambient_why": "为何选这首",
}

_UI_ZH_HANT = {
    "eyebrow": "Aulos · 沙龍典藏導賞",
    "lang_en": "English",
    "lang_zh": "繁體",
    "lang_zh_hans": "簡體",
    "lang_zh_hant": "繁體",
    "composer": "作曲家",
    "life": "生平概要",
    "temperament": "氣質與寫作性格",
    "oeuvre": "在其創作中的位置",
    "history": "在音樂史上的位置",
    "introduction": "作品導讀",
    "genesis": "創作背景與時代",
    "stature": "何以傳世",
    "wide": "廣域研究",
    "anatomy": "作品解剖",
    "deep": "深度聽法",
    "deepdives": "重點細讀",
    "map": "聆聽地圖",
    "sound": "聲響世界",
    "original_instrument": "原作聲響與樂器",
    "ensemble": "編制與演奏形態",
    "modes": "今日可取的聆聽方式",
    "kindred": "關聯作品",
    "interpretations": "名家演繹",
    "media": "聆聽室 · 影音與唱片",
    "videos": "影像與導賞路徑",
    "vinyl": "唱片目錄與黑膠線索",
    "practice": "如何練習聆聽",
    "caveats": "傳說與存疑",
    "footer": "由 Aulos 技能運行時生成 — 沙龍典藏導賞工坊。",
    "year": "年代",
    "place": "地點",
    "publication": "出版",
    "patronage": "贊助與題獻",
    "background": "創作語境",
    "instrument_culture": "樂器與演奏文化",
    "youtube": "YouTube 欣賞",
    "discogs": "Discogs 唱片",
    "ambient_label": "主題",
    "ambient_play": "播放",
    "ambient_pause": "暫停",
    "ambient_hint": "相關錄音作輕聲背景；若瀏覽器攔截自動播放，請輕點播放。",
    "ambient_expand": "說明",
    "ambient_collapse": "收起",
    "ambient_playlist": "曲目",
    "ambient_playlist_hint": "完整授權錄音 · 列表循環；點選曲目即可切換。",
    "ambient_now": "正在播放",
    "ambient_why": "為何選這首",
}

UI_COPY: dict[str, dict[str, str]] = {
    LANG_EN: _UI_EN,
    LANG_ZH_HANS: _UI_ZH_HANS,
    LANG_ZH_HANT: _UI_ZH_HANT,
    "zh": _UI_ZH_HANS,
}

# Simplified → Traditional music-guide lexicon (script + common term choices).
_HANT_PHRASE_MAP = (
    ("录音", "錄音"),
    ("导赏", "導賞"),
    ("听法", "聽法"),
    ("聆听", "聆聽"),
    ("声响", "聲響"),
    ("演绎", "演繹"),
    ("编制", "編制"),
    ("气质", "氣質"),
    ("传说", "傳說"),
    ("黑胶", "黑膠"),
    ("题献", "題獻"),
    ("赞助", "贊助"),
    ("关联", "關聯"),
    ("细读", "細讀"),
    ("广域", "廣域"),
    ("何以传世", "何以傳世"),
    ("弗雷德里克·肖邦", "弗雷德里克·蕭邦"),
    ("肖邦", "蕭邦"),
    ("德沃夏克", "德弗札克"),
    ("德伏夏克", "德弗札克"),
    ("贝多芬", "貝多芬"),
    ("马勒", "馬勒"),
    ("莫扎特", "莫札特"),
    ("奏鸣曲", "奏鳴曲"),
    ("交响曲", "交響曲"),
    ("交响乐", "交響樂"),
    ("变奏曲", "變奏曲"),
    ("玛祖卡", "馬祖卡"),
    ("马祖卡", "馬祖卡"),
    ("哥德堡", "郭德堡"),
    ("钢琴", "鋼琴"),
)


def to_traditional(text: str) -> str:
    """Convert Simplified prose to Traditional Chinese (script + music terms)."""
    if not text:
        return ""
    out = text
    try:
        import zhconv

        out = zhconv.convert(out, "zh-hant")
    except Exception:  # noqa: BLE001
        pass
    for hans, hant in _HANT_PHRASE_MAP:
        out = out.replace(hans, hant)
    return out


def to_simplified(text: str) -> str:
    if not text:
        return ""
    try:
        import zhconv

        return zhconv.convert(text, "zh-hans")
    except Exception:  # noqa: BLE001
        return text


def _convert_tree(value: Any, *, to_hant: bool) -> Any:
    if isinstance(value, str):
        return to_traditional(value) if to_hant else to_simplified(value)
    if isinstance(value, list):
        return [_convert_tree(v, to_hant=to_hant) for v in value]
    if isinstance(value, dict):
        return {k: _convert_tree(v, to_hant=to_hant) for k, v in value.items()}
    return value


def extract_zh_layer(dossier: dict[str, Any] | None) -> dict[str, Any]:
    """Simplified Chinese layer (`zh` / `zh_hans`)."""
    return extract_chinese_layer(dossier, LANG_ZH_HANS)


def extract_chinese_layer(dossier: dict[str, Any] | None, lang: str) -> dict[str, Any]:
    d = dict(dossier or {})
    lang = normalize_lang(lang)
    keys = _HANS_KEYS if lang == LANG_ZH_HANS else _HANT_KEYS
    for key in keys:
        layer = d.get(key)
        if isinstance(layer, dict) and layer:
            return dict(layer)
    if lang == LANG_ZH_HANT:
        for key in _HANS_KEYS:
            layer = d.get(key)
            if isinstance(layer, dict) and layer:
                return _convert_tree(dict(layer), to_hant=True)
    return {}


def localize_view(dossier: dict[str, Any] | None, lang: str) -> dict[str, Any]:
    """Build a single-language view. English = top-level; Chinese = merge scaffold + layer."""
    lang = normalize_lang(lang)
    base = dict(dossier or {})
    for key in ("zh", "zh_hans", "zh_hant", "zh-Hans", "zh-Hant"):
        base.pop(key, None)
    if lang == LANG_EN:
        return base

    zh = extract_chinese_layer(dossier, lang)
    if not zh:
        return empty_dossier()
    scaffold = empty_dossier()
    for key in (
        "composer_portrait",
        "interpretations",
        "appreciation_videos",
        "vinyl_and_discography",
        "ambient_audio",
    ):
        if base.get(key):
            scaffold[key] = base[key]
    for key in ("catalog", "composer", "work_title", "era", "form"):
        if base.get(key):
            scaffold[key] = base[key]
            if lang == LANG_ZH_HANT and isinstance(scaffold[key], str):
                scaffold[key] = to_traditional(scaffold[key])
    return merge_dossiers(scaffold, zh)


def dossier_has_zh(dossier: dict[str, Any] | None) -> bool:
    """True if any Chinese prose pack exists (Hans or Hant)."""
    d = dict(dossier or {})
    for key in _HANS_KEYS + _HANT_KEYS:
        zh = d.get(key)
        if not isinstance(zh, dict):
            continue
        if zh.get("listening_thesis") or zh.get("work_introduction"):
            return True
        if zh.get("width_points") or zh.get("depth_points"):
            return True
        if zh.get("composer_profile"):
            return True
    return False


def prefer_chinese_variant(text: str) -> str:
    """Pick default Chinese UI variant from the listener's message script."""
    raw = text or ""
    if not re_has_cjk(raw):
        return LANG_ZH_HANS
    hant_markers = ("導賞", "聽", "聲", "樂", "變奏", "蕭邦", "貝多芬", "德弗札克", "馬勒", "請")
    hans_markers = ("导赏", "听", "声", "乐", "变奏", "肖邦", "贝多芬", "德沃夏克", "马勒")
    hant = sum(1 for m in hant_markers if m in raw)
    hans = sum(1 for m in hans_markers if m in raw)
    if hant > hans:
        return LANG_ZH_HANT
    return LANG_ZH_HANS


def re_has_cjk(text: str) -> bool:
    return bool(re.search(r"[\u4e00-\u9fff]", text or ""))


def merge_zh_into(target: dict[str, Any], zh_layer: dict[str, Any] | None) -> dict[str, Any]:
    """Merge into `zh` / `zh_hans` (simplified) slots."""
    out = dict(target or {})
    if not zh_layer:
        return out
    existing = extract_chinese_layer(out, LANG_ZH_HANS)
    merged = merge_dossiers(existing, zh_layer)
    out["zh"] = merged
    out["zh_hans"] = merged
    return out


def ensure_chinese_variants(dossier: dict[str, Any] | None) -> dict[str, Any]:
    """Ensure zh / zh_hans exist; synthesize zh_hant from simplified when missing."""
    out = dict(dossier or {})
    hans = extract_chinese_layer(out, LANG_ZH_HANS)
    if hans:
        out["zh"] = hans
        out["zh_hans"] = hans
    hant = None
    for key in _HANT_KEYS:
        if isinstance(out.get(key), dict) and out.get(key):
            hant = dict(out[key])
            break
    if hant:
        out["zh_hant"] = hant
    elif hans:
        out["zh_hant"] = _convert_tree(hans, to_hant=True)
    return out


def strip_tech_leaks_zh(text: str) -> str:
    """Light hygiene: avoid leaking raw English skill/ops jargon into Chinese copy."""
    banned = (
        "SkillRuntime",
        "corpus_hit",
        "llm_dossier",
        "width_points",
        "TODO",
        "FIXME",
        "null",
        "undefined",
    )
    out = text or ""
    for b in banned:
        out = out.replace(b, "")
    return out.strip()
